My First Pull Request
braincee/hello-microverse pull request #1
Opened 2022-03-15 13:54 UTC by braincee

1. Added setup for linters
2.  Added and updated the main index.html. 
3. Added and updated the main style.css.
4.  Added and updated the gitignore files.

2022-03-15 17:35 UTC, mateo951 requested changes
### Hi @braincee,

Welcome to Microverse and congrats on making your first project 💪😎 

📝👌 **Your project highlights** 🔥😎 
- Nice README file 🚀 Well done!
- Great use of GitHub Flow 🤯
- Linters are working as expected 🙌
- Commit messages 🔥😎🔥

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-03-15 17:35 UTC, mateo951 commented on .gitignore
> +node_modules
Great job! You ignored the necessary directory and file ✔

2022-03-15 17:35 UTC, mateo951 commented
Please add a short summary describing the introduced changes in more detail.

For example, you could go with something like this🤓
  - Added setup for linters
  - Added gitignore file with ignored files/directories 
  - Added main structure (index.html / style.css)

2022-03-16 08:01 UTC, braincee commented
> Please add a short summary describing the introduced changes in more detail.
> 
> ![image](https://user-images.githubusercontent.com/15807343/158479181-2cba19fb-18d1-41e8-8faa-0c52194c48af.png)
> 
> For example, you could go with something like this🤓
> 
> * Added setup for linters
> * Added gitignore file with ignored files/directories
> * Added main structure (index.html / style.css)

2022-03-16 08:05 UTC, braincee commented
I have added all the short descriptive summaries in detail.

2022-03-16 08:18 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @braincee , 

Great work on making the changes requested by the previous reviewer 👏 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 13:28 UTC, merged

2022-11-12 08:53 UTC, braincee commented
Thanks @micheaol 
![472108170_THANK_YOU_STICKER_400px](https://user-images.githubusercontent.com/78104544/201466738-05c0fd64-44d1-4b9a-a8bb-5504d919bedf.gif)